manipulator_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - m_robot_joint_1
    - m_robot_joint_2
    - m_robot_joint_3
    - m_robot_joint_4
    - m_robot_joint_5
    - m_robot_joint_6
    - m_robot_joint_7
  gains:
    m_robot_joint_1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    m_robot_joint_2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    m_robot_joint_3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    m_robot_joint_4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    m_robot_joint_5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    m_robot_joint_6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    m_robot_joint_7:
      p: 100
      d: 1
      i: 1
      i_clamp: 1