controller_list:
  - name: fake_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - m_robot_joint_1
      - m_robot_joint_2
      - m_robot_joint_3
      - m_robot_joint_4
      - m_robot_joint_5
      - m_robot_joint_6
      - m_robot_joint_7
  - name: fake_iiwa_group_controller
    type: $(arg fake_execution_type)
    joints:
      - m_robot_joint_1
      - m_robot_joint_2
      - m_robot_joint_3
      - m_robot_joint_4
      - m_robot_joint_5
      - m_robot_joint_6
      - m_robot_joint_7
  - name: fake_soft_rg6_controller
    type: $(arg fake_execution_type)
    joints:
      - rg6_joint_1_1
      - rg6_joint_1_2
      - rg6_joint_2_1
      - rg6_joint_2_2
initial:  # Define initial robot poses per group
  - group: arm
    pose: default_pose