
arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - m_robot_joint_1
    - m_robot_joint_2
    - m_robot_joint_3
    - m_robot_joint_4
    - m_robot_joint_5
    - m_robot_joint_6
    - m_robot_joint_7
  gains:
    m_robot_joint_1:
      p: 500
      d: 15
      i: 30
      i_clamp: 1
    m_robot_joint_2:
      p: 200
      d: 10
      i: 10
      i_clamp: 1
    m_robot_joint_3:
      p: 65
      d: 15
      i: 10
      i_clamp: 1
    m_robot_joint_4:
      p: 31
      d: 12
      i: 7
      i_clamp: 1
    m_robot_joint_5:
      p: 23
      d: 5
      i: 3
      i_clamp: 1
    m_robot_joint_6:
      p: 13
      d: 3
      i: 3
      i_clamp: 1
    m_robot_joint_7:
      p: 17
      d: 2.5
      i: 2
      i_clamp: 1
soft_rg6_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - rg6_joint_1_1
    - rg6_joint_1_2
    - rg6_joint_2_1
    - rg6_joint_2_2
  gains:
    rg6_joint_1_1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    rg6_joint_1_2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    rg6_joint_2_1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    rg6_joint_2_2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
