home:
  iiwa_joint_1: 0
  iiwa_joint_2: 0
  iiwa_joint_3: 0
  iiwa_joint_4: 0
  iiwa_joint_5: 0
  iiwa_joint_6: 0
  iiwa_joint_7: 0

pos2:
  iiwa_joint_1: 0
  iiwa_joint_2: 1
  iiwa_joint_3: 2
  iiwa_joint_4: 3
  iiwa_joint_5: 4
  iiwa_joint_6: 5
  iiwa_joint_7: 6

open:
  rg6_joint_1_1: 2.2
  rg6_joint_1_2: -0.67
  rg6_joint_2_1: 2.2
  rg6_joint_2_2: -0.67

close:
  rg6_joint_1_1: 0.95
  rg6_joint_1_2: 0.67
  rg6_joint_2_1: 0.95
  rg6_joint_2_2: 0.67