controller_list:
  - name: fake_manipulator_controller
    type: $(arg fake_execution_type)
    joints:
      - m_robot_joint_1
      - m_robot_joint_2
      - m_robot_joint_3
      - m_robot_joint_4
      - m_robot_joint_5
      - m_robot_joint_6
      - m_robot_joint_7
initial:  # Define initial robot poses per group
#  - group: manipulator
#    pose: home

  []