water_tray: "corosect_ws/src/corosect/corosect/group1/scripts/meshes/Bird_drinker_ICF v5.stl"
bird_feeder: "corosect_ws/src/corosect/corosect/group1/scripts/meshes/BirdFeeder.stl"
cup: "corosect_ws/src/corosect/corosect/group1/scripts/meshes/Cup.stl"